brarcher/loyalty-card-locker

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java

There are loyalty cards which are not product codes but are 1D
barcodes. Enabling support for all types of 1D barcodes to
enable more types of loyalty cards.

Support scanning all types of 1D barcodes

---

app/build.gradle

tThere was an issue with requesting camera permission
for Android 6 which was resolved in release 3.2.0.
This attempts to resolve:
https://github.com/brarcher/loyalty-card-locker/issues/12

update zxing-android-embedded to latest release

---

app/src/main/res/values-it/strings.xml

Airon90 mentioned that although "Nota" is Italian for "Note", it would be better to use the plural
form "Note" here.
https://github.com/brarcher/loyalty-card-locker/pull/29

Update Italian translation for note

---

.travis.yml
app/build.gradle

The selection of SDK 17 was arbitrarily based on the version
available on my device at the time. As no APIs are being used
at that level, a lower SDK version can be targeted.
According to the current distribution of Android device versions,
99.9% of devices are at SDK 11+. Changing to this for the min SDK
for now.

Reduce min SDK version to 11

---

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/res/layout/content_main.xml
app/src/main/res/layout/loyalty_card_layout.xml

It turns out that the library used to create datamatrix barcodes returns the smallest image necessary to contain the barcode. That is, the size passed into the barcode writer. If the ImageView scales the tiny image itself into the full size it will use bi-linear filtering, which results in a blurry barcode.
To avoid this, if scaling is needed do so without using filtering.
https://github.com/brarcher/loyalty-card-locker/issues/37

Datamatrix scaling

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/test/java/protect/card_locker/ImportExportTest.java

Some users have mentioned that a barcode scanner has the best success when the screen is at its brightest. To enable the best results, the screen brightness will now be adjusted to its maximum when displaying a loyalty card.
https://github.com/brarcher/loyalty-card-locker/issues/21

Adjust brightness to its maximum when displaying a card

---

app/src/main/res/values-it/strings.xml

"Salva tessera" in Italian can be translated to "Save card" in English, It is:
-  associated to a button that start barcode scanning
- on the same screen of another button "Salva" in Itlaian (Save in  English)
I propose a less confusing translation: "scansione carta", that in English is "Card scan"

Small update to italian translation 

---

README.md
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values/strings.xml

The icon on the application is no longer a locker, so the
Locker part of the name no longer makes sense. Changing it
to Keychain, as it may make more sense.

Update the name "Locker" to "Keychain"

---

app/src/main/java/protect/card_locker/ImportExportActivity.java

The application is now "Loyalty Card Keychain", but "Locker"
still appears in the application's default import/export
file. Updating the file to match the new name of the application.

Change default import/export file name

---

.travis.yml

The application does not use google play and other extra libraries,
so downloading them during the build should be unnecessary.

Remove downloading extras during travis build

---

app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java

If a user is attempting to update a card id of an existing card, before when the Enter Card button was selected the barcode selector view would be empty. To be more useful, the view will now be pre-populated with the existing card id.

Pre-populate Barcode Selector

---

app/build.gradle
app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java

To reduce the amount of memory used in generating barcodes, limit
the width of the barcodes to no more than 3x the height.
This should be plenty sufficient to generate a usable barcode.
On devices with a really long width generating a barcode of 200x2560
is not useful and can result in an OutOfMemoryError.
https://github.com/brarcher/loyalty-card-locker/issues/99

Limit width of barcodes

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values/strings.xml

If someone is editing an existing card, or is adding a card
and wants to change the value, update the name of the button
from "Enter card" to "Edit card", to give the impression that
a new card id need not by typed from scratch.
https://github.com/brarcher/loyalty-card-locker/issues/89

Update "Enter card" button if card id exists

---

app/src/main/AndroidManifest.xml

If orientation and resize are not handled if the screen is
rotate or resized the IntroSlide fragment loses its layout,
and when it tries inflates the layout it fails to do so.

handle orientation and resize config change for IntroActivity

---

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java

https://github.com/brarcher/loyalty-card-locker/issues/113

Scale barcode height to match reduced width

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

At least one user in production has hit a case where the app was requested to display or update an existing id, but the id could not be found.
This adds a check that the card is found, and if it is not a message is displayed and bails out gracefully.

Verify card exists before displaying it

---

app/build.gradle
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nl/strings.xml

By request, a project on Transifex was created to better
manage translations. To make things less confusing, instead
of using the MissingTranslations lint error, and thus needing
to add stub translations, the progress of translations is now
handled on Transifex.
transifex.com/na-243/loyalty-card-locker/

Remove missing translations stubbed to English

---

app/src/main/AndroidManifest.xml

Now that there are shortcuts which can launch card viewing activities
directly, if a user does not back out of the activity then there will
be a pile up of activities over time. To prevent this, only let
one such view activity exist at a time.

Only let one card viewing activity exist at a time

---

app/src/main/AndroidManifest.xml
app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/ImportExportTask.java
app/src/main/res/xml/file_provider_paths.xml
app/src/test/java/protect/card_locker/ImportExportTest.java

https://github.com/brarcher/loyalty-card-locker/issues/152

Support importing/exporting via content providers

---

app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/test/java/protect/card_locker/ImportExportActivityTest.java

On Android SDK 24+ exposing a file Uri causes a failure.
Picking a file from a file chooser using data of a file://
Uri also hits this. As this is not necessary, removing the
Uri.

Remove file:// Uri from backup file picker

---

README.md

The screenshots now use the images from the metadata
folder in the repo.

Update screenshots in README

---

.travis.yml
app/build.gradle
app/src/main/java/protect/card_locker/CsvDatabaseImporter.java
app/src/test/java/protect/card_locker/ImportExportTest.java

Commons-CSV would throw a RuntimeException in some cases of
bad CSV input. This was later changed to throwing an
IllegalStateException. Updating to v1.5 to pick-up the change.

Fix crash on some corruption when importing CSV

---

app/src/main/java/protect/card_locker/ImportExportActivity.java

It was observed by one user that the Uri to filename lookup
failed with an IllegalStateException. The code which
converts a Uri to a file path may not be that great,
especially now that the app is expected to not receive
file Uris. Instead of determining the best way to lookup
the file names, as it is not that important it will be
removed.

Do not bother to show file name after an import

---

app/src/main/java/protect/card_locker/ImportExportActivity.java

The import path directly from the file system may not
result in using a content:// or file:// Uri, but instead
a file system path. If this occurs, attempt to use a FileInputStream
to read the contents.

Import from filesystem

---

app/src/main/res/layout/loyalty_card_view_layout.xml

This is to help barcode scanners determine where the end of
the barcode is.
https://github.com/brarcher/loyalty-card-locker/issues/195

Add quite space before and after barcode

---

app/src/main/AndroidManifest.xml
app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java

- Reloads card view activity when screen is rotated, so that the size of the image is known correctly.
- Renders 1D barcodes in a larger space, allowing them to better fill out the screen.
Combined, these changes let 1D barcodes be more useful in landscape:
https://github.com/brarcher/loyalty-card-locker/issues/67
https://github.com/brarcher/loyalty-card-locker/issues/202

Barcode rendering improvements

---

app/src/main/res/layout/loyalty_card_view_layout.xml

The landscape view left little room for the barcode and card ID
because the header took up a lot of space. Further, on smaller
phones it would take up a large portion of the screen.
This change reduces the header from 224dp to two action bar sizes
plus the size of the textview for the store name.

Reduce space used in header for card view

---

app/src/main/java/protect/card_locker/BarcodeImageWriterTask.java

There are still cases where the barcode could not be rendered
because the process runs out of its memory limit. To avoid
a crash, catch the failure and log it. The barcode will
not be displayed, but at least the app will not crash.

Catch case where barcode rendering runs into an OOM

---

app/build.gradle

The version of robolectric used no longer requires using the org.apache.http.legacy library.

Remove unnecessary apache legacy usage

---

app/build.gradle
app/src/main/res/layout/loyalty_card_edit_activity.xml
app/src/main/res/layout/loyalty_card_layout.xml

Google Play statistics show that the earliest Android version
in use which has installs for this app is 4.0.3, which is SDK 15.
This changes cleans up some layouts so that it will work on
SDK 15.

Add additional layout options to support SDK 15

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/preferences/Settings.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml

When a barcode is displayed the screen's brightness is set to
the maximum, in an attempt to provide the best chance for a barcode
scanner to capture the barcode. However, it may not always
be desired to increase the brightness, for example when using
the app in low light.
This change adds a setting to control the screen brightening
behavior when a barcode is viewed.
https://github.com/brarcher/loyalty-card-locker/issues/218

Configure brightening screen when display a barcode

---

app/src/main/java/protect/card_locker/DBHelper.java

Previously the upper case starting names all came before the lower case names. With this change they will be intermingled, ignoring the case.

Sort card list case insensitive

---

app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/main/java/protect/card_locker/preferences/Settings.java
app/src/main/res/values/strings.xml
app/src/main/res/xml/preferences.xml
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

This adds a new option which controls if the screen orientation lock option is displayed or not. If set, the orientation lock is forced and the unlock option is hidden.
This closes https://github.com/brarcher/loyalty-card-locker/issues/265.

Add option to lock orientation state

---

app/src/main/res/values-nb-rNO/strings.xml

I don't use Transifex anymore because it does not respect liberty, and suggest registering the project on hosted Weblate instead.

Norwegian Bokmål translation

---

app/src/main/AndroidManifest.xml

Setting the allowBackup option enables the app to participate
in backup and restore infrastructure.
Fixes: https://github.com/brarcher/loyalty-card-locker/issues/236

Allow backups of app data

---

app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java
app/src/main/java/protect/card_locker/LoyaltyCardEditActivity.java
app/src/test/java/protect/card_locker/BarcodeSelectorActivityTest.java
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

The LoyaltyCardEditActivity assumes on many places that an empty string
means it doesn't know a value yet. This patch ensures that the
BarcodeSelectorActivity returns a special string so that the
LoyaltyCardEditActivity can distinguish explicitly picking no barcode
from a not yet populated field.
Fixes #335. It does feel a bit hacky though...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/brarcher/loyalty-card-locker/336)

Fix converting loyalty card to barcodeless

---

app/src/main/java/protect/card_locker/ImportURIHelper.java
app/src/test/java/protect/card_locker/ImportURITest.java

Fix NPE when sharing cards without header values

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java
app/src/test/java/protect/card_locker/LoyaltyCardViewActivityTest.java

On a tap of the barcode, moves the barcode to the top of the screen. On another tap, move things back to normal. On the second screenshot, the top bar is normally hidden, it is only visible because creating a screenshot makes it reappear. Fixes #143.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/brarcher/loyalty-card-locker/348)

Move barcode to top on tap

---

app/src/main/java/protect/card_locker/LoyaltyCardViewActivity.java

#329 seems to have broken #348 somewhat, making the barcode non-centered when leaving fullscreen.
This pull request fixes this.
Screenshots of behaviour before applying this patch (normal -> fullscreen -> normal)

Fix barcode centering when leaving fullscreen

---

app/src/main/java/protect/card_locker/ImportExportActivity.java
app/src/main/java/protect/card_locker/ImportExportTask.java
app/src/main/res/layout/import_export_activity.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el-rGR/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-he-rIL/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-lt/strings.xml
app/src/main/res/values-nb-rNO/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pl/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-sk/strings.xml
app/src/main/res/values-sl/strings.xml
app/src/main/res/values/strings.xml
app/src/test/java/protect/card_locker/ImportExportActivityTest.java
app/src/test/java/protect/card_locker/ImportExportTest.java

Should hopefully fix #349 by making the following changes:
- Don't export to a fixed location, open the filebrowser with the filename LoyaltyCardLocker.csv pre-filled
- Remove the import from default location button (as the default location selected by Android will be the same for both the import and export button)
This change assumes that every single Android device has a file manager available. I have yet to see an Android device where this is not the case.

Choose export location
